server:
  port: 8082

spring:
  application:
    name: AuthenticationService

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:49152/infiniteChat?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: shr040726cc
    hikari:
      # 设置最大连接池大小
      maximum-pool-size: 10
      # 设置最小空闲连接数
      minimum-idle: 5
      # 设置连接池初始化失败时的超时时间
      initialization-fail-timeout: 10000
      # 设置连接池的最大空闲时间
      idle-timeout: 30000
      # 设置连接池中连接的最大生命周期
      max-lifetime: 60000
      # 设置连接池的连接超时时间
      connection-timeout: 30000
      # 设置连接池的最大等待时间
      validation-timeout: 3000
      # 配置连接池验证SQL（根据数据库选择合适的SQL）
      connection-test-query: SELECT 1
      # 设置连接池的池化管理名称
      pool-name: HikariCP

  redis:
    database: 0
    host: localhost
    port: 59000
    password: e65K4t8w2
    # 配置 redis 连接池
    lettuce:
      pool:
        # 链接池中最小的空闲链接 默认为0
        min-idle: 4
        # 链接池中最大的空闲连接 默认为 8
        max-idle: 8
        #连接池中最大数据库链接数 默认为8
        max-active: 8
        #连接池最大阻塞等待时间 负值表示没有限制
        max-wait: -1ms

  cloud:
    nacos:
      discovery:
        server-addr: localhost:18375

# 打印 sql
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin