server:
  port: 10010

spring:
  application:
    name: GateWay
  cloud:
    nacos:
      discovery:
        server-addr: localhost:18375
    gateway:
      httpclient:
        connect-timeout: 60000 # 连接超时时间，单位毫秒
        response-timeout: 60000 # 响应超时时间，单位毫秒
      # 全局配置
      # 配置全局跨域
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:10010"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "PATCH"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 36000
      routes:
        #        - id: query_router
        #          uri: https://www.baidu.com
        #          predicates:
        #            - Query=green
        #            - After=2026-01-20T17:42:47.789-07:00[America/Denver]
        #
        #        - id: cookie_route
        #          uri: https://qq.com
        #          predicates:
        #            - Cookie=chocolate, ch.p
        #
        #        - id: header_route
        #          uri: https://m.weibo.cn/
        #          predicates:
        #            - Header=X-Request-Id, \d+

        # 登录认证服务
        - id: AuthenticationService
          uri: lb://AuthenticationService
          # uri: http://localhost:8082
          predicates:
            - Path=/api/v1/user/**
            # - After=2026-01-20T17:42:47.789-07:00[America/Denver]
          filters:
            - AddRequestHeader=X-Request-Source, InfiniteChat-GateWay
            - AddResponseHeader=X-Response-Source, InfiniteChat-GateWay
        #当请求到达网关时，网关检查请求路径
        #如果路径匹配"/api/v1/user/**"，则应用该路由
        #网关添加指定的请求头
        #请求被转发到AuthenticationService服务
        #当响应返回时，网关添加指定的响应头
        #响应发送回客户端

        # 实时通信服务
        - id: RealTimeCommunicationService
          uri: lb://RealTimeCommunicationService
          predicates:
            - Path=/api/v1/message/**
        # Netty 长链接服务
        - id: NettyService
          # uri: ws://127.0.0.1:9000
          uri: lb:ws://NettyService
          predicates:
            - Path=/api/v1/netty

        # 消息转发服务
        - id: MessagingService

          uri: lb://MessagingService
          predicates:
            - Path=/api/v1/**
          filters:
            - AddRequestHeader=X-Request-Source, InfiniteChat-GateWay
            - AddResponseHeader=X-Response-Source, InfiniteChat-GateWay

        # 离线存储模块
        - id: OfflineDataStore
          uri: lb://OfflineDataStore
          predicates:
            - Path=/api/v1/offline/**

        # 朋友圈模块
        - id: MomentService
          uri: lb://MomentService
          predicates:
            - Path=/api/v1/moment/**